version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/ap
    environment:
      - DEBUG=True
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"