# Generated by Django 5.1 on 2024-08-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pagelink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sitename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
